version: "3.9"

services:
  presentismo_api:
    build: .
    container_name: api_presentismo
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./datos_parte.json:/app/datos_parte.json:ro